- name: "Stat | Vars File Existance"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/env-{{ env }}.yaml"
  delegate_to: localhost
  run_once: true
  register: env_vars

- name: "Fail | Provide ENV file"
  ansible.builtin.fail:
    msg: "Provide environment file!"
  when: not (env_vars.stat.exists | bool)

- name: "Import | Env Vars"
  ansible.builtin.include_vars: "{{ playbook_dir }}/env-{{ env }}.yaml"
