apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saigoblog.backend.secretEnvName" . }}
  labels:
    {{- include "saigoblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  namespace: {{ .Release.Namespace }}
  {{- if .Values.backend.annotations }}
  annotations: {{ toYaml .Values.backend.annotations | nindent 4 }}
  {{- end }}
data:
{{- if .Values.backend.deployEnvs }}
{{- range $envKey, $envValue := .Values.backend.deployEnvs }}
  {{ $envKey }}: {{ $envValue | b64enc }}
{{- end }}
{{- end }}
{{/*
{{- $envFile := printf "env/%s.yaml" .Values.environment }}
{{- $envData := .Files.Get $envFile | fromYaml }}
{{- range $envKey, $envValue :=  $envData }}
  {{ $envKey }}: {{ $envValue | b64enc }}
{{- end }}
*/}}
