apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- range $key, $value := .Values.backend.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "saigoblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  name: {{ include "saigoblog.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.backend.service.type }}
{{- if .Values.backend.service.clusterIP }}
  clusterIP: {{ .Values.backend.service.clusterIP }}
{{- end }}
{{- if .Values.backend.service.externalIPs }}
  externalIPs: {{ toYaml .Values.backend.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.backend.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.backend.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.backend.service.sessionAffinity }}
  sessionAffinity: {{ .Values.backend.service.sessionAffinity }}
{{- end }}
  selector:
    {{- include "saigoblog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
  {{- if .Values.backend.service.enableHttp }}
    - name: http
      port: {{ .Values.backend.service.ports.http }}
      protocol: TCP
      targetPort: {{ .Values.backend.service.targetPorts.http }}
    {{- if and (semverCompare ">=1.20" .Capabilities.KubeVersion.Version) (.Values.backend.service.appProtocol) }}
      appProtocol: http
    {{- end }}
  {{- end }}
  {{- if .Values.backend.service.enableHttps }}
    - name: https
      port: {{ .Values.backend.service.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.backend.service.targetPorts.https }}
    {{- if and (semverCompare ">=1.20" .Capabilities.KubeVersion.Version) (.Values.backend.service.appProtocol) }}
      appProtocol: https
    {{- end }}
  {{- end }}
