{{- if .Values.frontend.customNginxConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saigoblog.frontend.fullname" . }}
  labels:
    {{- include "saigoblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  namespace: {{ .Release.Namespace }}
  {{- if .Values.frontend.annotations }}
  annotations: {{ toYaml .Values.frontend.annotations | nindent 4 }}
  {{- end }}
data:
{{- range $path, $_ := .Files.Glob "files/nginx_configs/*" }}
  {{ base $path | trimSuffix ".tpl" }}: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}
{{- end }}
