{{- $pullSecretContent := .Values.serviceAccount.createPullSecrets.imagePullSecretsContent }}
{{- if $pullSecretContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saigoblog.fullname" . }}-registry
  labels:
    {{- include "saigoblog.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $pullSecretContent | b64enc }}
{{- end }}
