{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "saigoblog.serviceAccountName" . }}
  labels:
    {{- include "saigoblog.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- $pullSecret := .Values.serviceAccount.createPullSecrets.imagePullSecrets }}
{{- $pullSecretContent := .Values.serviceAccount.createPullSecrets.imagePullSecretsContent }}
{{- if (or $pullSecret $pullSecretContent) }}
imagePullSecrets: 
  {{- if $pullSecretContent }}
  - name: {{ include "saigoblog.fullname" . }}-registry
  {{- else }}
  - name: {{ $pullSecret }}
  {{- end }}
{{- end }}
{{- end }}
