---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lts-staging
spec:
  acme:
    email: an.grigoriev84@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lts-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
