---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lts-prod
spec:
  acme:
    email: an.grigoriev84@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lts-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
