.basic: &basic
  enabled: true
  namespace: kube-system
  type: system

metrics_server:
  <<: *basic
  version: "~3.10.0"

cert_manager:
  <<: *basic
  version: "~v1.11.1"
  namespace: cert-manager

ingress:
  <<: *basic
  version: "~4.6.0"
  namespace: ingress

postgres:
  <<: *basic
  version: "~12.2.5"
  namespace: default
  type: db

saigoblog:
  <<: *basic
  namespace: default
  needs:
    - cert-manager/cert-manager
    - ingress/nginx
    - postgres
  type: app

